version: '2'

services:
  gpw-tweets:
    build: .
    command: node build/gpw-tweets.js
    volumes:
      - ${PWD}/twitter-credentials.json:/app/twitter-credentials.json
      - ${PWD}/mstall:/app/mstall
      - ${PWD}/images:/app/images