version: '2'

services:
  volume-notifier:
    build: .
    command: npm start
    volumes:
      - ${PWD}/twitter-credentials.json:/app/twitter-credentials.json
      - ${PWD}/mstall:/app/mstall
      - ${PWD}/images:/app/images